spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/efm}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}
spring.h2.console.enabled=${SPRING_H2_CONSOLE_ENABLED:false}
efm.docker.seed.admin.username=${EFM_DOCKER_ADMIN_USERNAME:admin}
efm.docker.seed.admin.password=${EFM_DOCKER_ADMIN_PASSWORD:admin}
