spring.application.name=efm
spring.web.locale=en
spring.web.locale-resolver=fixed

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}

spring.h2.console.enabled=${SPRING_H2_CONSOLE_ENABLED:true}
spring.h2.console.path=${SPRING_H2_CONSOLE_PATH:/h2-console}

logging.level.org.springframework.security=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:INFO}
spring.jpa.open-in-view=false

jwt.rsa.pri=${JWT_RSA_PRIVATE_KEY:classpath:api-dev.pri}
jwt.rsa.pub=${JWT_RSA_PUBLIC_KEY:classpath:api-dev.pub}
